name: Print Release Version

on:
  release:
    types: [created]

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history. Otherwise, detecting branch fails

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/backups-website:latest .

      - name: Get release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Build and push Docker images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}/backups-website:latest \
            --tag ghcr.io/${{ github.repository }}/backups-website:${{ env.RELEASE_TAG }} \
            --push .

#      - name: Create release build
#        run: docker tag ghcr.io/${{ github.repository }}/backups-website:latest ghcr.io/${{ github.repository }}/backups-website:${{ env.RELEASE_TAG }}
#
#      - name: Push Docker release image to GHCR
#        run: docker push ghcr.io/${{ github.repository }}/backups-website:latest
#
#      - name: Push Docker tag image to GHCR
#        run: docker push ghcr.io/${{ github.repository }}/backups-website:${{ env.RELEASE_TAG }}
