name: Print Release Version

on:
  release:
    types: [created]

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history. Otherwise, detecting branch fails

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/backups-website:latest .

      - name: Get release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Create release build
        run: docker tag ghcr.io/${{ github.repository }}/backups-website:latest ghcr.io/${{ github.repository }}/backups-website:${{ env.RELEASE_TAG }}

      - name: Push Docker release image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/backups-website:latest

      - name: Push Docker tag image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/backups-website:${{ env.RELEASE_TAG }}
